### ISSUE TITLE
Frontend Interface for LinkedIn Profile Viewer

### ISSUE THREAD

**Issue by Scrap-lon** [scrape-linkedin/Linkedin-Profile-Viewer#11]
Currently, our project has a robust LinkedIn API that allows us to retrieve LinkedIn profiles. However, we lack a user-friendly frontend interface for users to interact with and view these profiles.

We would like to request the development of a frontend interface that leverages our LinkedIn API. This interface should provide users with a seamless and visually appealing way to view LinkedIn profiles.

**Comment by thehptalks** [comment]
I would like create a frontend for this project.
