### ISSUE TITLE
Show laoding indicator when fetching data from an api

### ISSUE THREAD

**Issue by Scrap-lon** [scrape-linkedin/Linkedin-Profile-Viewer#18]

**Comment by Jay90123** [comment]
I can solve this issue. Can you please assign this issue to me

**Comment by Jagtap01sumit** [comment]
I want to solve this is issue. and contribute in this project .

**Comment by varadpawar29** [comment]
I can solve this issue by using conditional rendering with the help of react state.
Can you please assign this issue to me
