### ISSUE TITLE
Show a profile placeholder image 

### ISSUE THREAD

**Issue by Scrap-lon** [scrape-linkedin/Linkedin-Profile-Viewer#22]
When a profile with no profile picture is fetched. show a placeholder profile image

 
![image](https://github.com/scrape-linkedin/Linkedin-Profile-Viewer/assets/144942569/acb7f5a0-6072-4931-8da7-80edb71af8c9)
![image](https://github.com/scrape-linkedin/Linkedin-Profile-Viewer/assets/144942569/b6804fbf-6534-4f8b-ad2a-15eb1570f471)

**Comment by sakshinikharge39** [comment]
Please assign me this issue

**Comment by sakshinikharge39** [comment]
I can solve this issue by applying a conditional check on the profile picture field. If the length of the profile Picture filled > 0 then we render fetched profile else we can render a placeholder profile
