### ISSUE TITLE
Redundant Scraping and Duplicate Profile Documents Creation

### ISSUE THREAD

**Issue by LokeshPatil-loki** [scrape-linkedin/Linkedin-Profile-Viewer#3]
**Description:**
We've encountered an issue where profiles are being scrapped and new profile documents are getting created in the MongoDB database, even when the profile information is already present and not older than 12 hours. This behavior is leading to duplicate profile entries and unnecessary scraping.

**Problem:**
- Profiles that have been scrapped and stored within the last 12 hours are being re-scrapped.
- The API is generating new profile documents in MongoDB, contributing to data redundancy.

**Expected Behavior:**
Profiles that have been recently scrapped and stored within the last 12 hours should not undergo redundant scraping or result in the creation of new profile documents. The API should recognize existing profiles and avoid duplicating them.

**Acceptance Criteria:**
- The API should incorporate a mechanism to check the last scraping timestamp and avoid redundant scraping within a 12-hour window.
- The creation of duplicate profile documents in MongoDB should be prevented for profiles within the specified timeframe.

**Steps to Reproduce:**
1. Identify profiles that have been recently scrapped and stored.
2. Trigger the scraping process for the same profiles.
3. Observe the generation of new profile documents in MongoDB.

https://github.com/LokeshPatil-loki/Linkedin-Profile-Viewer/assets/69594258/7225b477-6242-4d81-ba3c-cebf7bd2913b

**Comment by chaitanya4455** [comment]
I would like to work on this issue
