### ISSUE TITLE
Feature Request: Scrape All Comments of Posts

### ISSUE THREAD

**Issue by LokeshPatil-loki** [scrape-linkedin/Linkedin-Profile-Viewer#5]
**Description:**
We are excited to propose a new feature that enhances our LinkedIn profile data scraping capabilities by enabling the extraction of all comments from posts. This feature aims to provide users with a comprehensive view of engagement on posts by collecting and presenting all comments associated with each post.

**Proposed Feature:**
When users query the API for post information, the API should also retrieve and include all comments made on that post as part of the JSON response. Each comment entry will consist of the commenter's profile information, comment text, timestamp.

**Acceptance Criteria:**
1. The API should retrieve and include all comments associated with a post in the JSON response.
2. Each comment entry should include the commenter's profile information, comment text, timestamp.
3. The comment data should be accurate, up-to-date, and align with the respective post.
4. The API documentation should be updated to reflect the new feature and guide users on how to interpret and utilize comment data.

**Comment by nimish07-ai** [comment]
Capture
